-- Heavy seed (part 2): posts, likes, comments, friend_requests, messages, court_queue, court_admins, tournaments, play_sessions, coaching_listings.
-- Run after 0013. Uses INSERT OR IGNORE. Depends on users, regions, courts from 0013 and demo seed.
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-1', 'user-demo-1', 'Looking for doubles partners this weekend. Who''s in?', datetime('now', '-2 days', '-1 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-2', 'user-demo-2', 'Just got my new paddle — can''t wait to try it. Anyone playing tomorrow?', datetime('now', '-3 days', '-2 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-3', 'user-demo-3', 'Pro tip: warm up your shoulder before playing. Saved me from a lot of soreness.', datetime('now', '-4 days', '-3 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-4', 'user-demo-4', 'Thanks everyone who came to the round-robin last week. Same time next week!', datetime('now', '-5 days', '-4 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-5', 'user-demo-5', 'Open play at the community center Saturday 9am. All skill levels welcome.', datetime('now', '-6 days', '-5 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-6', 'user-seed-1', 'Anyone know good 4.0+ games in the area?', datetime('now', '-7 days', '-6 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-7', 'user-seed-2', 'Beginner here looking for patient partners to learn with.', datetime('now', '-8 days', '-7 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-8', 'user-seed-3', 'Tournament recap: had a blast. Congrats to the winners!', datetime('now', '-9 days', '-8 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-9', 'user-seed-4', 'Third-shot drop practice paid off today. Finally feeling consistent.', datetime('now', '-10 days', '-9 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-10', 'user-seed-5', 'New courts opened at the community center. Check them out!', datetime('now', '-11 days', '-10 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-11', 'user-seed-6', 'Looking for a mixed doubles partner for the spring league.', datetime('now', '-12 days', '-11 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-12', 'user-seed-7', 'Dink rally with 50+ hits today. This game is addictive.', datetime('now', '-13 days', '-12 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-13', 'user-seed-8', 'Shoutout to everyone who showed up for the charity round-robin.', datetime('now', '-14 days', '-13 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-14', 'user-seed-9', 'Best paddle for control? Currently using a Engage Pursuit.', datetime('now', '-1 days', '-14 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-15', 'user-seed-10', 'Playing in the rain today — dedicated crew!', datetime('now', '-2 days', '-15 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-16', 'user-seed-11', 'Looking for doubles partners this weekend. Who''s in?', datetime('now', '-3 days', '-16 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-17', 'user-seed-12', 'Just got my new paddle — can''t wait to try it. Anyone playing tomorrow?', datetime('now', '-4 days', '-17 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-18', 'user-seed-13', 'Pro tip: warm up your shoulder before playing. Saved me from a lot of soreness.', datetime('now', '-5 days', '-18 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-19', 'user-seed-14', 'Thanks everyone who came to the round-robin last week. Same time next week!', datetime('now', '-6 days', '-19 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-20', 'user-seed-15', 'Open play at the community center Saturday 9am. All skill levels welcome.', datetime('now', '-7 days', '-20 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-21', 'user-seed-16', 'Anyone know good 4.0+ games in the area?', datetime('now', '-8 days', '-21 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-22', 'user-seed-17', 'Beginner here looking for patient partners to learn with.', datetime('now', '-9 days', '-22 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-23', 'user-seed-18', 'Tournament recap: had a blast. Congrats to the winners!', datetime('now', '-10 days', '-23 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-24', 'user-seed-19', 'Third-shot drop practice paid off today. Finally feeling consistent.', datetime('now', '-11 days', '-0 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-25', 'user-seed-20', 'New courts opened at the community center. Check them out!', datetime('now', '-12 days', '-1 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-26', 'user-seed-21', 'Looking for a mixed doubles partner for the spring league.', datetime('now', '-13 days', '-2 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-27', 'user-seed-22', 'Dink rally with 50+ hits today. This game is addictive.', datetime('now', '-14 days', '-3 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-28', 'user-seed-23', 'Shoutout to everyone who showed up for the charity round-robin.', datetime('now', '-1 days', '-4 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-29', 'user-seed-24', 'Best paddle for control? Currently using a Onix Z5.', datetime('now', '-2 days', '-5 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-30', 'user-seed-25', 'Playing in the rain today — dedicated crew!', datetime('now', '-3 days', '-6 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-31', 'user-seed-26', 'Looking for doubles partners this weekend. Who''s in?', datetime('now', '-4 days', '-7 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-32', 'user-seed-27', 'Just got my new paddle — can''t wait to try it. Anyone playing tomorrow?', datetime('now', '-5 days', '-8 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-33', 'user-seed-28', 'Pro tip: warm up your shoulder before playing. Saved me from a lot of soreness.', datetime('now', '-6 days', '-9 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-34', 'user-seed-29', 'Thanks everyone who came to the round-robin last week. Same time next week!', datetime('now', '-7 days', '-10 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-35', 'user-seed-30', 'Open play at the community center Saturday 9am. All skill levels welcome.', datetime('now', '-8 days', '-11 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-36', 'user-seed-31', 'Anyone know good 4.0+ games in the area?', datetime('now', '-9 days', '-12 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-37', 'user-seed-32', 'Beginner here looking for patient partners to learn with.', datetime('now', '-10 days', '-13 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-38', 'user-seed-33', 'Tournament recap: had a blast. Congrats to the winners!', datetime('now', '-11 days', '-14 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-39', 'user-seed-34', 'Third-shot drop practice paid off today. Finally feeling consistent.', datetime('now', '-12 days', '-15 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-40', 'user-seed-35', 'New courts opened at the community center. Check them out!', datetime('now', '-13 days', '-16 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-41', 'user-seed-36', 'Looking for a mixed doubles partner for the spring league.', datetime('now', '-14 days', '-17 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-42', 'user-seed-37', 'Dink rally with 50+ hits today. This game is addictive.', datetime('now', '-1 days', '-18 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-43', 'user-seed-38', 'Shoutout to everyone who showed up for the charity round-robin.', datetime('now', '-2 days', '-19 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-44', 'user-seed-39', 'Best paddle for control? Currently using a Gearbox Pro.', datetime('now', '-3 days', '-20 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-45', 'user-seed-40', 'Playing in the rain today — dedicated crew!', datetime('now', '-4 days', '-21 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-46', 'user-seed-41', 'Looking for doubles partners this weekend. Who''s in?', datetime('now', '-5 days', '-22 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-47', 'user-seed-42', 'Just got my new paddle — can''t wait to try it. Anyone playing tomorrow?', datetime('now', '-6 days', '-23 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-48', 'user-seed-43', 'Pro tip: warm up your shoulder before playing. Saved me from a lot of soreness.', datetime('now', '-7 days', '-0 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-49', 'user-seed-44', 'Thanks everyone who came to the round-robin last week. Same time next week!', datetime('now', '-8 days', '-1 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-50', 'user-seed-45', 'Open play at the community center Saturday 9am. All skill levels welcome.', datetime('now', '-9 days', '-2 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-51', 'user-seed-46', 'Anyone know good 4.0+ games in the area?', datetime('now', '-10 days', '-3 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-52', 'user-seed-47', 'Beginner here looking for patient partners to learn with.', datetime('now', '-11 days', '-4 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-53', 'user-seed-48', 'Tournament recap: had a blast. Congrats to the winners!', datetime('now', '-12 days', '-5 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-54', 'user-seed-49', 'Third-shot drop practice paid off today. Finally feeling consistent.', datetime('now', '-13 days', '-6 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-55', 'user-seed-50', 'New courts opened at the community center. Check them out!', datetime('now', '-14 days', '-7 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-56', 'user-seed-51', 'Looking for a mixed doubles partner for the spring league.', datetime('now', '-1 days', '-8 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-57', 'user-seed-52', 'Dink rally with 50+ hits today. This game is addictive.', datetime('now', '-2 days', '-9 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-58', 'user-seed-53', 'Shoutout to everyone who showed up for the charity round-robin.', datetime('now', '-3 days', '-10 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-59', 'user-seed-54', 'Best paddle for control? Currently using a Six Zero DBD.', datetime('now', '-4 days', '-11 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-60', 'user-seed-55', 'Playing in the rain today — dedicated crew!', datetime('now', '-5 days', '-12 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-61', 'user-seed-56', 'Looking for doubles partners this weekend. Who''s in?', datetime('now', '-6 days', '-13 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-62', 'user-seed-57', 'Just got my new paddle — can''t wait to try it. Anyone playing tomorrow?', datetime('now', '-7 days', '-14 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-63', 'user-seed-58', 'Pro tip: warm up your shoulder before playing. Saved me from a lot of soreness.', datetime('now', '-8 days', '-15 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-64', 'user-seed-59', 'Thanks everyone who came to the round-robin last week. Same time next week!', datetime('now', '-9 days', '-16 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-65', 'user-seed-60', 'Open play at the community center Saturday 9am. All skill levels welcome.', datetime('now', '-10 days', '-17 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-66', 'user-seed-61', 'Anyone know good 4.0+ games in the area?', datetime('now', '-11 days', '-18 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-67', 'user-seed-62', 'Beginner here looking for patient partners to learn with.', datetime('now', '-12 days', '-19 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-68', 'user-seed-63', 'Tournament recap: had a blast. Congrats to the winners!', datetime('now', '-13 days', '-20 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-69', 'user-seed-64', 'Third-shot drop practice paid off today. Finally feeling consistent.', datetime('now', '-14 days', '-21 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-70', 'user-seed-65', 'New courts opened at the community center. Check them out!', datetime('now', '-1 days', '-22 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-71', 'user-seed-66', 'Looking for a mixed doubles partner for the spring league.', datetime('now', '-2 days', '-23 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-72', 'user-seed-67', 'Dink rally with 50+ hits today. This game is addictive.', datetime('now', '-3 days', '-0 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-73', 'user-seed-68', 'Shoutout to everyone who showed up for the charity round-robin.', datetime('now', '-4 days', '-1 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-74', 'user-seed-69', 'Best paddle for control? Currently using a CRBN 2X.', datetime('now', '-5 days', '-2 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-75', 'user-seed-70', 'Playing in the rain today — dedicated crew!', datetime('now', '-6 days', '-3 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-76', 'user-seed-71', 'Looking for doubles partners this weekend. Who''s in?', datetime('now', '-7 days', '-4 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-77', 'user-seed-72', 'Just got my new paddle — can''t wait to try it. Anyone playing tomorrow?', datetime('now', '-8 days', '-5 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-78', 'user-seed-73', 'Pro tip: warm up your shoulder before playing. Saved me from a lot of soreness.', datetime('now', '-9 days', '-6 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-79', 'user-seed-74', 'Thanks everyone who came to the round-robin last week. Same time next week!', datetime('now', '-10 days', '-7 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-80', 'user-seed-75', 'Open play at the community center Saturday 9am. All skill levels welcome.', datetime('now', '-11 days', '-8 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-81', 'user-seed-76', 'Anyone know good 4.0+ games in the area?', datetime('now', '-12 days', '-9 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-82', 'user-seed-77', 'Beginner here looking for patient partners to learn with.', datetime('now', '-13 days', '-10 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-83', 'user-seed-78', 'Tournament recap: had a blast. Congrats to the winners!', datetime('now', '-14 days', '-11 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-84', 'user-seed-79', 'Third-shot drop practice paid off today. Finally feeling consistent.', datetime('now', '-1 days', '-12 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-85', 'user-seed-80', 'New courts opened at the community center. Check them out!', datetime('now', '-2 days', '-13 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-86', 'user-seed-81', 'Looking for a mixed doubles partner for the spring league.', datetime('now', '-3 days', '-14 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-87', 'user-seed-82', 'Dink rally with 50+ hits today. This game is addictive.', datetime('now', '-4 days', '-15 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-88', 'user-seed-83', 'Shoutout to everyone who showed up for the charity round-robin.', datetime('now', '-5 days', '-16 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-89', 'user-seed-84', 'Best paddle for control? Currently using a Joola Hyperion.', datetime('now', '-6 days', '-17 hours'));
INSERT OR IGNORE INTO posts (id, author_id, content, created_at) VALUES ('post-seed-90', 'user-seed-85', 'Playing in the rain today — dedicated crew!', datetime('now', '-7 days', '-18 hours'));

INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-1', 'user-demo-1');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-2', 'user-demo-4');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-2', 'user-demo-5');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-3', 'user-seed-2');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-3', 'user-seed-3');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-3', 'user-seed-4');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-4', 'user-seed-5');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-4', 'user-seed-6');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-4', 'user-seed-7');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-4', 'user-seed-8');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-5', 'user-seed-8');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-5', 'user-seed-9');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-5', 'user-seed-10');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-5', 'user-seed-11');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-5', 'user-seed-12');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-6', 'user-seed-11');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-6', 'user-seed-12');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-6', 'user-seed-13');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-6', 'user-seed-14');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-6', 'user-seed-15');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-6', 'user-seed-16');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-7', 'user-seed-14');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-7', 'user-seed-15');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-7', 'user-seed-16');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-7', 'user-seed-17');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-7', 'user-seed-18');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-7', 'user-seed-19');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-7', 'user-seed-20');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-8', 'user-seed-17');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-8', 'user-seed-18');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-8', 'user-seed-19');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-8', 'user-seed-20');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-8', 'user-seed-21');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-8', 'user-seed-22');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-8', 'user-seed-23');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-8', 'user-seed-24');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-9', 'user-seed-20');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-10', 'user-seed-23');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-10', 'user-seed-24');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-11', 'user-seed-26');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-11', 'user-seed-27');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-11', 'user-seed-28');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-12', 'user-seed-29');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-12', 'user-seed-30');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-12', 'user-seed-31');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-12', 'user-seed-32');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-13', 'user-seed-32');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-13', 'user-seed-33');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-13', 'user-seed-34');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-13', 'user-seed-35');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-13', 'user-seed-36');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-14', 'user-seed-35');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-14', 'user-seed-36');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-14', 'user-seed-37');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-14', 'user-seed-38');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-14', 'user-seed-39');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-14', 'user-seed-40');
