INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-70', 'user-seed-81');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-70', 'user-seed-82');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-70', 'user-seed-83');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-71', 'user-seed-81');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-71', 'user-seed-82');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-71', 'user-seed-83');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-71', 'user-seed-84');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-71', 'user-seed-85');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-71', 'user-seed-86');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-71', 'user-seed-87');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-72', 'user-seed-84');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-72', 'user-seed-85');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-72', 'user-seed-86');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-72', 'user-seed-87');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-72', 'user-seed-88');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-72', 'user-seed-89');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-72', 'user-seed-90');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-72', 'user-seed-91');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-73', 'user-seed-87');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-74', 'user-seed-90');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-74', 'user-seed-91');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-75', 'user-seed-93');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-75', 'user-seed-94');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-75', 'user-seed-95');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-76', 'user-seed-96');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-76', 'user-seed-97');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-76', 'user-seed-98');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-76', 'user-seed-99');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-77', 'user-seed-99');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-77', 'user-seed-100');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-77', 'user-seed-101');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-77', 'user-seed-102');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-77', 'user-seed-103');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-78', 'user-seed-102');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-78', 'user-seed-103');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-78', 'user-seed-104');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-78', 'user-seed-105');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-78', 'user-seed-106');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-78', 'user-seed-107');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-79', 'user-seed-105');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-79', 'user-seed-106');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-79', 'user-seed-107');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-79', 'user-seed-108');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-79', 'user-seed-109');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-79', 'user-seed-110');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-79', 'user-seed-111');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-80', 'user-seed-108');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-80', 'user-seed-109');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-80', 'user-seed-110');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-80', 'user-seed-111');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-80', 'user-seed-112');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-80', 'user-seed-113');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-80', 'user-seed-114');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-80', 'user-seed-115');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-81', 'user-seed-111');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-82', 'user-seed-114');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-82', 'user-seed-115');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-83', 'user-seed-117');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-83', 'user-seed-118');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-83', 'user-seed-119');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-84', 'user-seed-120');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-84', 'user-demo-1');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-84', 'user-demo-2');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-84', 'user-demo-3');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-85', 'user-demo-3');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-85', 'user-demo-4');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-85', 'user-demo-5');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-85', 'user-seed-1');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-85', 'user-seed-2');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-86', 'user-seed-1');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-86', 'user-seed-2');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-86', 'user-seed-3');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-86', 'user-seed-4');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-86', 'user-seed-5');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-86', 'user-seed-6');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-87', 'user-seed-4');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-87', 'user-seed-5');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-87', 'user-seed-6');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-87', 'user-seed-7');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-87', 'user-seed-8');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-87', 'user-seed-9');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-87', 'user-seed-10');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-88', 'user-seed-7');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-88', 'user-seed-8');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-88', 'user-seed-9');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-88', 'user-seed-10');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-88', 'user-seed-11');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-88', 'user-seed-12');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-88', 'user-seed-13');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-88', 'user-seed-14');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-89', 'user-seed-10');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-90', 'user-seed-13');
INSERT OR IGNORE INTO likes (post_id, user_id) VALUES ('post-seed-90', 'user-seed-14');

INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-1', 'post-seed-2', 'user-demo-4', 'Count me in.', datetime('now', '-2 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-2', 'post-seed-3', 'user-demo-5', 'See you there.', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-3', 'post-seed-3', 'user-seed-1', 'Sounds good.', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-4', 'post-seed-4', 'user-seed-1', 'Sounds good.', datetime('now', '-4 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-5', 'post-seed-4', 'user-seed-2', 'Can''t make it this week.', datetime('now', '-4 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-6', 'post-seed-4', 'user-seed-3', 'What time?', datetime('now', '-4 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-7', 'post-seed-6', 'user-seed-3', 'What time?', datetime('now', '-1 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-8', 'post-seed-7', 'user-seed-4', 'I''m in!', datetime('now', '-2 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-9', 'post-seed-7', 'user-seed-5', 'Count me in.', datetime('now', '-2 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-10', 'post-seed-8', 'user-seed-5', 'Count me in.', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-11', 'post-seed-8', 'user-seed-6', 'See you there.', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-12', 'post-seed-8', 'user-seed-7', 'Sounds good.', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-13', 'post-seed-10', 'user-seed-7', 'Sounds good.', datetime('now', '-5 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-14', 'post-seed-11', 'user-seed-8', 'Can''t make it this week.', datetime('now', '-1 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-15', 'post-seed-11', 'user-seed-9', 'What time?', datetime('now', '-1 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-16', 'post-seed-12', 'user-seed-9', 'What time?', datetime('now', '-2 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-17', 'post-seed-12', 'user-seed-10', 'I''m in!', datetime('now', '-2 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-18', 'post-seed-12', 'user-seed-11', 'Count me in.', datetime('now', '-2 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-19', 'post-seed-14', 'user-seed-11', 'Count me in.', datetime('now', '-4 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-20', 'post-seed-15', 'user-seed-12', 'See you there.', datetime('now', '-5 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-21', 'post-seed-15', 'user-seed-13', 'Sounds good.', datetime('now', '-5 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-22', 'post-seed-16', 'user-seed-13', 'Sounds good.', datetime('now', '-1 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-23', 'post-seed-16', 'user-seed-14', 'Can''t make it this week.', datetime('now', '-1 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-24', 'post-seed-16', 'user-seed-15', 'What time?', datetime('now', '-1 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-25', 'post-seed-18', 'user-seed-15', 'What time?', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-26', 'post-seed-19', 'user-seed-16', 'I''m in!', datetime('now', '-4 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-27', 'post-seed-19', 'user-seed-17', 'Count me in.', datetime('now', '-4 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-28', 'post-seed-20', 'user-seed-17', 'Count me in.', datetime('now', '-5 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-29', 'post-seed-20', 'user-seed-18', 'See you there.', datetime('now', '-5 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-30', 'post-seed-20', 'user-seed-19', 'Sounds good.', datetime('now', '-5 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-31', 'post-seed-22', 'user-seed-19', 'Sounds good.', datetime('now', '-2 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-32', 'post-seed-23', 'user-seed-20', 'Can''t make it this week.', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-33', 'post-seed-23', 'user-seed-21', 'What time?', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-34', 'post-seed-24', 'user-seed-21', 'What time?', datetime('now', '-4 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-35', 'post-seed-24', 'user-seed-22', 'I''m in!', datetime('now', '-4 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-36', 'post-seed-24', 'user-seed-23', 'Count me in.', datetime('now', '-4 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-37', 'post-seed-26', 'user-seed-23', 'Count me in.', datetime('now', '-1 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-38', 'post-seed-27', 'user-seed-24', 'See you there.', datetime('now', '-2 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-39', 'post-seed-27', 'user-seed-25', 'Sounds good.', datetime('now', '-2 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-40', 'post-seed-28', 'user-seed-25', 'Sounds good.', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-41', 'post-seed-28', 'user-seed-26', 'Can''t make it this week.', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-42', 'post-seed-28', 'user-seed-27', 'What time?', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-43', 'post-seed-30', 'user-seed-27', 'What time?', datetime('now', '-5 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-44', 'post-seed-31', 'user-seed-28', 'I''m in!', datetime('now', '-1 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-45', 'post-seed-31', 'user-seed-29', 'Count me in.', datetime('now', '-1 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-46', 'post-seed-32', 'user-seed-29', 'Count me in.', datetime('now', '-2 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-47', 'post-seed-32', 'user-seed-30', 'See you there.', datetime('now', '-2 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-48', 'post-seed-32', 'user-seed-31', 'Sounds good.', datetime('now', '-2 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-49', 'post-seed-34', 'user-seed-31', 'Sounds good.', datetime('now', '-4 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-50', 'post-seed-35', 'user-seed-32', 'Can''t make it this week.', datetime('now', '-5 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-51', 'post-seed-35', 'user-seed-33', 'What time?', datetime('now', '-5 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-52', 'post-seed-36', 'user-seed-33', 'What time?', datetime('now', '-1 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-53', 'post-seed-36', 'user-seed-34', 'I''m in!', datetime('now', '-1 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-54', 'post-seed-36', 'user-seed-35', 'Count me in.', datetime('now', '-1 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-55', 'post-seed-38', 'user-seed-35', 'Count me in.', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-56', 'post-seed-39', 'user-seed-36', 'See you there.', datetime('now', '-4 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-57', 'post-seed-39', 'user-seed-37', 'Sounds good.', datetime('now', '-4 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-58', 'post-seed-40', 'user-seed-37', 'Sounds good.', datetime('now', '-5 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-59', 'post-seed-40', 'user-seed-38', 'Can''t make it this week.', datetime('now', '-5 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-60', 'post-seed-40', 'user-seed-39', 'What time?', datetime('now', '-5 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-61', 'post-seed-42', 'user-seed-39', 'What time?', datetime('now', '-2 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-62', 'post-seed-43', 'user-seed-40', 'I''m in!', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-63', 'post-seed-43', 'user-seed-41', 'Count me in.', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-64', 'post-seed-44', 'user-seed-41', 'Count me in.', datetime('now', '-4 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-65', 'post-seed-44', 'user-seed-42', 'See you there.', datetime('now', '-4 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-66', 'post-seed-44', 'user-seed-43', 'Sounds good.', datetime('now', '-4 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-67', 'post-seed-46', 'user-seed-43', 'Sounds good.', datetime('now', '-1 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-68', 'post-seed-47', 'user-seed-44', 'Can''t make it this week.', datetime('now', '-2 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-69', 'post-seed-47', 'user-seed-45', 'What time?', datetime('now', '-2 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-70', 'post-seed-48', 'user-seed-45', 'What time?', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-71', 'post-seed-48', 'user-seed-46', 'I''m in!', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-72', 'post-seed-48', 'user-seed-47', 'Count me in.', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-73', 'post-seed-50', 'user-seed-47', 'Count me in.', datetime('now', '-5 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-74', 'post-seed-51', 'user-seed-48', 'See you there.', datetime('now', '-1 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-75', 'post-seed-51', 'user-seed-49', 'Sounds good.', datetime('now', '-1 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-76', 'post-seed-52', 'user-seed-49', 'Sounds good.', datetime('now', '-2 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-77', 'post-seed-52', 'user-seed-50', 'Can''t make it this week.', datetime('now', '-2 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-78', 'post-seed-52', 'user-seed-51', 'What time?', datetime('now', '-2 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-79', 'post-seed-54', 'user-seed-51', 'What time?', datetime('now', '-4 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-80', 'post-seed-55', 'user-seed-52', 'I''m in!', datetime('now', '-5 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-81', 'post-seed-55', 'user-seed-53', 'Count me in.', datetime('now', '-5 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-82', 'post-seed-56', 'user-seed-53', 'Count me in.', datetime('now', '-1 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-83', 'post-seed-56', 'user-seed-54', 'See you there.', datetime('now', '-1 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-84', 'post-seed-56', 'user-seed-55', 'Sounds good.', datetime('now', '-1 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-85', 'post-seed-58', 'user-seed-55', 'Sounds good.', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-86', 'post-seed-59', 'user-seed-56', 'Can''t make it this week.', datetime('now', '-4 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-87', 'post-seed-59', 'user-seed-57', 'What time?', datetime('now', '-4 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-88', 'post-seed-60', 'user-seed-57', 'What time?', datetime('now', '-5 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-89', 'post-seed-60', 'user-seed-58', 'I''m in!', datetime('now', '-5 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-90', 'post-seed-60', 'user-seed-59', 'Count me in.', datetime('now', '-5 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-91', 'post-seed-62', 'user-seed-59', 'Count me in.', datetime('now', '-2 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-92', 'post-seed-63', 'user-seed-60', 'See you there.', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-93', 'post-seed-63', 'user-seed-61', 'Sounds good.', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-94', 'post-seed-64', 'user-seed-61', 'Sounds good.', datetime('now', '-4 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-95', 'post-seed-64', 'user-seed-62', 'Can''t make it this week.', datetime('now', '-4 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-96', 'post-seed-64', 'user-seed-63', 'What time?', datetime('now', '-4 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-97', 'post-seed-66', 'user-seed-63', 'What time?', datetime('now', '-1 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-98', 'post-seed-67', 'user-seed-64', 'I''m in!', datetime('now', '-2 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-99', 'post-seed-67', 'user-seed-65', 'Count me in.', datetime('now', '-2 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-100', 'post-seed-68', 'user-seed-65', 'Count me in.', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-101', 'post-seed-68', 'user-seed-66', 'See you there.', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-102', 'post-seed-68', 'user-seed-67', 'Sounds good.', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-103', 'post-seed-70', 'user-seed-67', 'Sounds good.', datetime('now', '-5 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-104', 'post-seed-71', 'user-seed-68', 'Can''t make it this week.', datetime('now', '-1 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-105', 'post-seed-71', 'user-seed-69', 'What time?', datetime('now', '-1 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-106', 'post-seed-72', 'user-seed-69', 'What time?', datetime('now', '-2 days'));
