INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-107', 'post-seed-72', 'user-seed-70', 'I''m in!', datetime('now', '-2 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-108', 'post-seed-72', 'user-seed-71', 'Count me in.', datetime('now', '-2 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-109', 'post-seed-74', 'user-seed-71', 'Count me in.', datetime('now', '-4 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-110', 'post-seed-75', 'user-seed-72', 'See you there.', datetime('now', '-5 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-111', 'post-seed-75', 'user-seed-73', 'Sounds good.', datetime('now', '-5 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-112', 'post-seed-76', 'user-seed-73', 'Sounds good.', datetime('now', '-1 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-113', 'post-seed-76', 'user-seed-74', 'Can''t make it this week.', datetime('now', '-1 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-114', 'post-seed-76', 'user-seed-75', 'What time?', datetime('now', '-1 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-115', 'post-seed-78', 'user-seed-75', 'What time?', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-116', 'post-seed-79', 'user-seed-76', 'I''m in!', datetime('now', '-4 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-117', 'post-seed-79', 'user-seed-77', 'Count me in.', datetime('now', '-4 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-118', 'post-seed-80', 'user-seed-77', 'Count me in.', datetime('now', '-5 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-119', 'post-seed-80', 'user-seed-78', 'See you there.', datetime('now', '-5 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-120', 'post-seed-80', 'user-seed-79', 'Sounds good.', datetime('now', '-5 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-121', 'post-seed-82', 'user-seed-79', 'Sounds good.', datetime('now', '-2 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-122', 'post-seed-83', 'user-seed-80', 'Can''t make it this week.', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-123', 'post-seed-83', 'user-seed-81', 'What time?', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-124', 'post-seed-84', 'user-seed-81', 'What time?', datetime('now', '-4 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-125', 'post-seed-84', 'user-seed-82', 'I''m in!', datetime('now', '-4 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-126', 'post-seed-84', 'user-seed-83', 'Count me in.', datetime('now', '-4 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-127', 'post-seed-86', 'user-seed-83', 'Count me in.', datetime('now', '-1 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-128', 'post-seed-87', 'user-seed-84', 'See you there.', datetime('now', '-2 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-129', 'post-seed-87', 'user-seed-85', 'Sounds good.', datetime('now', '-2 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-130', 'post-seed-88', 'user-seed-85', 'Sounds good.', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-131', 'post-seed-88', 'user-seed-86', 'Can''t make it this week.', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-132', 'post-seed-88', 'user-seed-87', 'What time?', datetime('now', '-3 days'));
INSERT OR IGNORE INTO comments (id, post_id, author_id, content, created_at) VALUES ('comment-seed-133', 'post-seed-90', 'user-seed-87', 'What time?', datetime('now', '-5 days'));

INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-demo-1', 'user-demo-2', 'pending', datetime('now', '-1 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-3', 'user-seed-8', 'accepted', datetime('now', '-2 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-8', 'user-seed-3', 'accepted', datetime('now', '-2 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-10', 'user-seed-19', 'accepted', datetime('now', '-3 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-19', 'user-seed-10', 'accepted', datetime('now', '-3 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-17', 'user-seed-30', 'accepted', datetime('now', '-4 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-30', 'user-seed-17', 'accepted', datetime('now', '-4 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-24', 'user-seed-41', 'accepted', datetime('now', '-5 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-41', 'user-seed-24', 'accepted', datetime('now', '-5 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-31', 'user-seed-52', 'accepted', datetime('now', '-6 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-52', 'user-seed-31', 'accepted', datetime('now', '-6 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-38', 'user-seed-63', 'accepted', datetime('now', '-7 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-63', 'user-seed-38', 'accepted', datetime('now', '-7 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-45', 'user-seed-74', 'accepted', datetime('now', '-8 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-74', 'user-seed-45', 'accepted', datetime('now', '-8 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-52', 'user-seed-85', 'accepted', datetime('now', '-9 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-85', 'user-seed-52', 'accepted', datetime('now', '-9 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-59', 'user-seed-96', 'accepted', datetime('now', '-10 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-96', 'user-seed-59', 'accepted', datetime('now', '-10 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-66', 'user-seed-107', 'pending', datetime('now', '-11 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-73', 'user-seed-118', 'accepted', datetime('now', '-12 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-118', 'user-seed-73', 'accepted', datetime('now', '-12 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-80', 'user-seed-4', 'accepted', datetime('now', '-13 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-4', 'user-seed-80', 'accepted', datetime('now', '-13 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-87', 'user-seed-15', 'accepted', datetime('now', '-14 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-15', 'user-seed-87', 'accepted', datetime('now', '-14 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-94', 'user-seed-26', 'accepted', datetime('now', '-1 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-26', 'user-seed-94', 'accepted', datetime('now', '-1 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-101', 'user-seed-37', 'accepted', datetime('now', '-2 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-37', 'user-seed-101', 'accepted', datetime('now', '-2 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-108', 'user-seed-48', 'accepted', datetime('now', '-3 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-48', 'user-seed-108', 'accepted', datetime('now', '-3 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-115', 'user-seed-59', 'accepted', datetime('now', '-4 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-59', 'user-seed-115', 'accepted', datetime('now', '-4 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-demo-2', 'user-seed-70', 'accepted', datetime('now', '-5 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-70', 'user-demo-2', 'accepted', datetime('now', '-5 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-4', 'user-seed-81', 'accepted', datetime('now', '-6 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-81', 'user-seed-4', 'accepted', datetime('now', '-6 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-11', 'user-seed-92', 'pending', datetime('now', '-7 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-18', 'user-seed-103', 'accepted', datetime('now', '-8 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-103', 'user-seed-18', 'accepted', datetime('now', '-8 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-25', 'user-seed-114', 'accepted', datetime('now', '-9 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-114', 'user-seed-25', 'accepted', datetime('now', '-9 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-32', 'user-demo-5', 'accepted', datetime('now', '-10 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-demo-5', 'user-seed-32', 'accepted', datetime('now', '-10 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-39', 'user-seed-11', 'accepted', datetime('now', '-11 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-11', 'user-seed-39', 'accepted', datetime('now', '-11 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-46', 'user-seed-22', 'accepted', datetime('now', '-12 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-22', 'user-seed-46', 'accepted', datetime('now', '-12 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-53', 'user-seed-33', 'accepted', datetime('now', '-13 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-33', 'user-seed-53', 'accepted', datetime('now', '-13 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-60', 'user-seed-44', 'accepted', datetime('now', '-14 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-44', 'user-seed-60', 'accepted', datetime('now', '-14 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-67', 'user-seed-55', 'accepted', datetime('now', '-1 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-55', 'user-seed-67', 'accepted', datetime('now', '-1 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-74', 'user-seed-66', 'accepted', datetime('now', '-2 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-66', 'user-seed-74', 'accepted', datetime('now', '-2 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-81', 'user-seed-77', 'pending', datetime('now', '-3 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-88', 'user-seed-89', 'accepted', datetime('now', '-4 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-89', 'user-seed-88', 'accepted', datetime('now', '-4 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-95', 'user-seed-99', 'accepted', datetime('now', '-5 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-99', 'user-seed-95', 'accepted', datetime('now', '-5 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-102', 'user-seed-110', 'accepted', datetime('now', '-6 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-110', 'user-seed-102', 'accepted', datetime('now', '-6 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-109', 'user-demo-1', 'accepted', datetime('now', '-7 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-demo-1', 'user-seed-109', 'accepted', datetime('now', '-7 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-116', 'user-seed-7', 'accepted', datetime('now', '-8 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-7', 'user-seed-116', 'accepted', datetime('now', '-8 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-demo-3', 'user-seed-18', 'accepted', datetime('now', '-9 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-18', 'user-demo-3', 'accepted', datetime('now', '-9 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-5', 'user-seed-29', 'accepted', datetime('now', '-10 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-29', 'user-seed-5', 'accepted', datetime('now', '-10 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-12', 'user-seed-40', 'accepted', datetime('now', '-11 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-40', 'user-seed-12', 'accepted', datetime('now', '-11 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-19', 'user-seed-51', 'accepted', datetime('now', '-12 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-51', 'user-seed-19', 'accepted', datetime('now', '-12 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-26', 'user-seed-62', 'pending', datetime('now', '-13 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-33', 'user-seed-73', 'accepted', datetime('now', '-14 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-73', 'user-seed-33', 'accepted', datetime('now', '-14 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-40', 'user-seed-84', 'accepted', datetime('now', '-1 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-84', 'user-seed-40', 'accepted', datetime('now', '-1 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-47', 'user-seed-95', 'accepted', datetime('now', '-2 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-95', 'user-seed-47', 'accepted', datetime('now', '-2 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-54', 'user-seed-106', 'accepted', datetime('now', '-3 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-106', 'user-seed-54', 'accepted', datetime('now', '-3 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-61', 'user-seed-117', 'accepted', datetime('now', '-4 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-117', 'user-seed-61', 'accepted', datetime('now', '-4 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-68', 'user-seed-3', 'accepted', datetime('now', '-5 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-3', 'user-seed-68', 'accepted', datetime('now', '-5 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-75', 'user-seed-14', 'accepted', datetime('now', '-6 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-14', 'user-seed-75', 'accepted', datetime('now', '-6 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-82', 'user-seed-25', 'accepted', datetime('now', '-7 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-25', 'user-seed-82', 'accepted', datetime('now', '-7 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-89', 'user-seed-36', 'accepted', datetime('now', '-8 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-36', 'user-seed-89', 'accepted', datetime('now', '-8 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-96', 'user-seed-47', 'pending', datetime('now', '-9 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-103', 'user-seed-58', 'accepted', datetime('now', '-10 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-58', 'user-seed-103', 'accepted', datetime('now', '-10 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-110', 'user-seed-69', 'accepted', datetime('now', '-11 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-69', 'user-seed-110', 'accepted', datetime('now', '-11 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-117', 'user-seed-80', 'accepted', datetime('now', '-12 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-80', 'user-seed-117', 'accepted', datetime('now', '-12 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-demo-4', 'user-seed-91', 'accepted', datetime('now', '-13 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-91', 'user-demo-4', 'accepted', datetime('now', '-13 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-6', 'user-seed-102', 'accepted', datetime('now', '-14 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-102', 'user-seed-6', 'accepted', datetime('now', '-14 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-13', 'user-seed-113', 'accepted', datetime('now', '-1 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-113', 'user-seed-13', 'accepted', datetime('now', '-1 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-20', 'user-demo-4', 'accepted', datetime('now', '-2 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-demo-4', 'user-seed-20', 'accepted', datetime('now', '-2 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-27', 'user-seed-10', 'accepted', datetime('now', '-3 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-10', 'user-seed-27', 'accepted', datetime('now', '-3 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-34', 'user-seed-21', 'accepted', datetime('now', '-4 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-21', 'user-seed-34', 'accepted', datetime('now', '-4 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-41', 'user-seed-32', 'pending', datetime('now', '-5 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-48', 'user-seed-43', 'accepted', datetime('now', '-6 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-43', 'user-seed-48', 'accepted', datetime('now', '-6 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-55', 'user-seed-54', 'accepted', datetime('now', '-7 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-54', 'user-seed-55', 'accepted', datetime('now', '-7 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-62', 'user-seed-65', 'accepted', datetime('now', '-8 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-65', 'user-seed-62', 'accepted', datetime('now', '-8 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-69', 'user-seed-76', 'accepted', datetime('now', '-9 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-76', 'user-seed-69', 'accepted', datetime('now', '-9 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-76', 'user-seed-87', 'accepted', datetime('now', '-10 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-87', 'user-seed-76', 'accepted', datetime('now', '-10 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-83', 'user-seed-98', 'accepted', datetime('now', '-11 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-98', 'user-seed-83', 'accepted', datetime('now', '-11 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-90', 'user-seed-109', 'accepted', datetime('now', '-12 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-109', 'user-seed-90', 'accepted', datetime('now', '-12 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-97', 'user-seed-120', 'accepted', datetime('now', '-13 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-120', 'user-seed-97', 'accepted', datetime('now', '-13 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-104', 'user-seed-6', 'accepted', datetime('now', '-14 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-6', 'user-seed-104', 'accepted', datetime('now', '-14 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-111', 'user-seed-17', 'pending', datetime('now', '-1 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-118', 'user-seed-28', 'accepted', datetime('now', '-2 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-28', 'user-seed-118', 'accepted', datetime('now', '-2 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-demo-5', 'user-seed-39', 'accepted', datetime('now', '-3 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-39', 'user-demo-5', 'accepted', datetime('now', '-3 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-7', 'user-seed-50', 'accepted', datetime('now', '-4 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-50', 'user-seed-7', 'accepted', datetime('now', '-4 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-14', 'user-seed-61', 'accepted', datetime('now', '-5 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-61', 'user-seed-14', 'accepted', datetime('now', '-5 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-21', 'user-seed-72', 'accepted', datetime('now', '-6 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-72', 'user-seed-21', 'accepted', datetime('now', '-6 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-28', 'user-seed-83', 'accepted', datetime('now', '-7 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-83', 'user-seed-28', 'accepted', datetime('now', '-7 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-35', 'user-seed-94', 'accepted', datetime('now', '-8 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-94', 'user-seed-35', 'accepted', datetime('now', '-8 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-42', 'user-seed-105', 'accepted', datetime('now', '-9 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-105', 'user-seed-42', 'accepted', datetime('now', '-9 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-49', 'user-seed-116', 'accepted', datetime('now', '-10 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-116', 'user-seed-49', 'accepted', datetime('now', '-10 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-56', 'user-seed-2', 'pending', datetime('now', '-11 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-63', 'user-seed-13', 'accepted', datetime('now', '-12 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-13', 'user-seed-63', 'accepted', datetime('now', '-12 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-70', 'user-seed-24', 'accepted', datetime('now', '-13 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-24', 'user-seed-70', 'accepted', datetime('now', '-13 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-77', 'user-seed-35', 'accepted', datetime('now', '-14 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-35', 'user-seed-77', 'accepted', datetime('now', '-14 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-84', 'user-seed-46', 'accepted', datetime('now', '-1 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-46', 'user-seed-84', 'accepted', datetime('now', '-1 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-91', 'user-seed-57', 'accepted', datetime('now', '-2 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-57', 'user-seed-91', 'accepted', datetime('now', '-2 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-98', 'user-seed-68', 'accepted', datetime('now', '-3 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-68', 'user-seed-98', 'accepted', datetime('now', '-3 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-105', 'user-seed-79', 'accepted', datetime('now', '-4 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-79', 'user-seed-105', 'accepted', datetime('now', '-4 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-112', 'user-seed-90', 'accepted', datetime('now', '-5 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-90', 'user-seed-112', 'accepted', datetime('now', '-5 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-119', 'user-seed-101', 'accepted', datetime('now', '-6 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-101', 'user-seed-119', 'accepted', datetime('now', '-6 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-1', 'user-seed-112', 'pending', datetime('now', '-7 days'));
