INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-8', 'user-demo-3', 'accepted', datetime('now', '-8 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-demo-3', 'user-seed-8', 'accepted', datetime('now', '-8 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-15', 'user-seed-9', 'accepted', datetime('now', '-9 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-9', 'user-seed-15', 'accepted', datetime('now', '-9 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-22', 'user-seed-20', 'accepted', datetime('now', '-10 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-20', 'user-seed-22', 'accepted', datetime('now', '-10 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-29', 'user-seed-31', 'accepted', datetime('now', '-11 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-31', 'user-seed-29', 'accepted', datetime('now', '-11 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-36', 'user-seed-42', 'accepted', datetime('now', '-12 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-42', 'user-seed-36', 'accepted', datetime('now', '-12 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-43', 'user-seed-53', 'accepted', datetime('now', '-13 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-53', 'user-seed-43', 'accepted', datetime('now', '-13 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-50', 'user-seed-64', 'accepted', datetime('now', '-14 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-64', 'user-seed-50', 'accepted', datetime('now', '-14 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-57', 'user-seed-75', 'accepted', datetime('now', '-1 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-75', 'user-seed-57', 'accepted', datetime('now', '-1 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-64', 'user-seed-86', 'accepted', datetime('now', '-2 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-86', 'user-seed-64', 'accepted', datetime('now', '-2 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-71', 'user-seed-97', 'pending', datetime('now', '-3 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-78', 'user-seed-108', 'accepted', datetime('now', '-4 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-108', 'user-seed-78', 'accepted', datetime('now', '-4 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-85', 'user-seed-119', 'accepted', datetime('now', '-5 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-119', 'user-seed-85', 'accepted', datetime('now', '-5 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-92', 'user-seed-5', 'accepted', datetime('now', '-6 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-5', 'user-seed-92', 'accepted', datetime('now', '-6 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-99', 'user-seed-16', 'accepted', datetime('now', '-7 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-16', 'user-seed-99', 'accepted', datetime('now', '-7 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-106', 'user-seed-27', 'accepted', datetime('now', '-8 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-27', 'user-seed-106', 'accepted', datetime('now', '-8 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-113', 'user-seed-38', 'accepted', datetime('now', '-9 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-38', 'user-seed-113', 'accepted', datetime('now', '-9 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-120', 'user-seed-49', 'accepted', datetime('now', '-10 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-49', 'user-seed-120', 'accepted', datetime('now', '-10 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-2', 'user-seed-60', 'accepted', datetime('now', '-11 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-60', 'user-seed-2', 'accepted', datetime('now', '-11 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-9', 'user-seed-71', 'accepted', datetime('now', '-12 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-71', 'user-seed-9', 'accepted', datetime('now', '-12 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-16', 'user-seed-82', 'pending', datetime('now', '-13 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-23', 'user-seed-93', 'accepted', datetime('now', '-14 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-93', 'user-seed-23', 'accepted', datetime('now', '-14 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-30', 'user-seed-104', 'accepted', datetime('now', '-1 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-104', 'user-seed-30', 'accepted', datetime('now', '-1 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-37', 'user-seed-115', 'accepted', datetime('now', '-2 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-115', 'user-seed-37', 'accepted', datetime('now', '-2 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-44', 'user-seed-1', 'accepted', datetime('now', '-3 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-1', 'user-seed-44', 'accepted', datetime('now', '-3 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-51', 'user-seed-12', 'accepted', datetime('now', '-4 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-12', 'user-seed-51', 'accepted', datetime('now', '-4 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-58', 'user-seed-23', 'accepted', datetime('now', '-5 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-23', 'user-seed-58', 'accepted', datetime('now', '-5 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-65', 'user-seed-34', 'accepted', datetime('now', '-6 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-34', 'user-seed-65', 'accepted', datetime('now', '-6 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-72', 'user-seed-45', 'accepted', datetime('now', '-7 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-45', 'user-seed-72', 'accepted', datetime('now', '-7 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-79', 'user-seed-56', 'accepted', datetime('now', '-8 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-56', 'user-seed-79', 'accepted', datetime('now', '-8 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-86', 'user-seed-67', 'pending', datetime('now', '-9 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-93', 'user-seed-78', 'accepted', datetime('now', '-10 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-78', 'user-seed-93', 'accepted', datetime('now', '-10 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-100', 'user-seed-89', 'accepted', datetime('now', '-11 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-89', 'user-seed-100', 'accepted', datetime('now', '-11 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-107', 'user-seed-100', 'accepted', datetime('now', '-12 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-100', 'user-seed-107', 'accepted', datetime('now', '-12 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-114', 'user-seed-111', 'accepted', datetime('now', '-13 days'));
INSERT OR IGNORE INTO friend_requests (from_id, to_id, status, created_at) VALUES ('user-seed-111', 'user-seed-114', 'accepted', datetime('now', '-13 days'));

INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-1', 'user-demo-1', 'user-demo-2', 'Hey, still on for Saturday?', datetime('now', '-1 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-2', 'user-seed-9', 'user-seed-14', 'Yes! Court 2 at 10.', datetime('now', '-2 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-3', 'user-seed-22', 'user-seed-31', 'Perfect, see you then.', datetime('now', '-3 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-4', 'user-seed-35', 'user-seed-48', 'Running 5 min late.', datetime('now', '-4 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-5', 'user-seed-48', 'user-seed-65', 'Need a fourth?', datetime('now', '-5 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-6', 'user-seed-61', 'user-seed-82', 'I''m in for tomorrow.', datetime('now', '-6 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-7', 'user-seed-74', 'user-seed-99', 'What''s your DUPR?', datetime('now', '-7 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-8', 'user-seed-87', 'user-seed-116', 'Great game today!', datetime('now', '-1 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-9', 'user-seed-100', 'user-seed-8', 'Hey, still on for Saturday?', datetime('now', '-2 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-10', 'user-seed-113', 'user-seed-25', 'Yes! Court 2 at 10.', datetime('now', '-3 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-11', 'user-seed-1', 'user-seed-42', 'Perfect, see you then.', datetime('now', '-4 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-12', 'user-seed-14', 'user-seed-59', 'Running 5 min late.', datetime('now', '-5 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-13', 'user-seed-27', 'user-seed-76', 'Need a fourth?', datetime('now', '-6 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-14', 'user-seed-40', 'user-seed-93', 'I''m in for tomorrow.', datetime('now', '-7 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-15', 'user-seed-53', 'user-seed-110', 'What''s your DUPR?', datetime('now', '-1 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-16', 'user-seed-66', 'user-seed-2', 'Great game today!', datetime('now', '-2 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-17', 'user-seed-79', 'user-seed-19', 'Hey, still on for Saturday?', datetime('now', '-3 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-18', 'user-seed-92', 'user-seed-36', 'Yes! Court 2 at 10.', datetime('now', '-4 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-19', 'user-seed-105', 'user-seed-53', 'Perfect, see you then.', datetime('now', '-5 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-20', 'user-seed-118', 'user-seed-70', 'Running 5 min late.', datetime('now', '-6 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-21', 'user-seed-6', 'user-seed-87', 'Need a fourth?', datetime('now', '-7 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-22', 'user-seed-19', 'user-seed-104', 'I''m in for tomorrow.', datetime('now', '-1 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-23', 'user-seed-32', 'user-demo-1', 'What''s your DUPR?', datetime('now', '-2 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-24', 'user-seed-45', 'user-seed-13', 'Great game today!', datetime('now', '-3 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-25', 'user-seed-58', 'user-seed-30', 'Hey, still on for Saturday?', datetime('now', '-4 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-26', 'user-seed-71', 'user-seed-47', 'Yes! Court 2 at 10.', datetime('now', '-5 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-27', 'user-seed-84', 'user-seed-64', 'Perfect, see you then.', datetime('now', '-6 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-28', 'user-seed-97', 'user-seed-81', 'Running 5 min late.', datetime('now', '-7 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-29', 'user-seed-110', 'user-seed-98', 'Need a fourth?', datetime('now', '-1 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-30', 'user-demo-3', 'user-seed-115', 'I''m in for tomorrow.', datetime('now', '-2 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-31', 'user-seed-11', 'user-seed-7', 'What''s your DUPR?', datetime('now', '-3 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-32', 'user-seed-24', 'user-seed-25', 'Great game today!', datetime('now', '-4 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-33', 'user-seed-37', 'user-seed-41', 'Hey, still on for Saturday?', datetime('now', '-5 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-34', 'user-seed-50', 'user-seed-58', 'Yes! Court 2 at 10.', datetime('now', '-6 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-35', 'user-seed-63', 'user-seed-75', 'Perfect, see you then.', datetime('now', '-7 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-36', 'user-seed-76', 'user-seed-92', 'Running 5 min late.', datetime('now', '-1 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-37', 'user-seed-89', 'user-seed-109', 'Need a fourth?', datetime('now', '-2 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-38', 'user-seed-102', 'user-seed-1', 'I''m in for tomorrow.', datetime('now', '-3 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-39', 'user-seed-115', 'user-seed-18', 'What''s your DUPR?', datetime('now', '-4 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-40', 'user-seed-3', 'user-seed-35', 'Great game today!', datetime('now', '-5 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-41', 'user-seed-16', 'user-seed-52', 'Hey, still on for Saturday?', datetime('now', '-6 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-42', 'user-seed-29', 'user-seed-69', 'Yes! Court 2 at 10.', datetime('now', '-7 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-43', 'user-seed-42', 'user-seed-86', 'Perfect, see you then.', datetime('now', '-1 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-44', 'user-seed-55', 'user-seed-103', 'Running 5 min late.', datetime('now', '-2 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-45', 'user-seed-68', 'user-seed-120', 'Need a fourth?', datetime('now', '-3 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-46', 'user-seed-81', 'user-seed-12', 'I''m in for tomorrow.', datetime('now', '-4 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-47', 'user-seed-94', 'user-seed-29', 'What''s your DUPR?', datetime('now', '-5 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-48', 'user-seed-107', 'user-seed-46', 'Great game today!', datetime('now', '-6 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-49', 'user-seed-120', 'user-seed-63', 'Hey, still on for Saturday?', datetime('now', '-7 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-50', 'user-seed-8', 'user-seed-80', 'Yes! Court 2 at 10.', datetime('now', '-1 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-51', 'user-seed-21', 'user-seed-97', 'Perfect, see you then.', datetime('now', '-2 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-52', 'user-seed-34', 'user-seed-114', 'Running 5 min late.', datetime('now', '-3 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-53', 'user-seed-47', 'user-seed-6', 'Need a fourth?', datetime('now', '-4 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-54', 'user-seed-60', 'user-seed-23', 'I''m in for tomorrow.', datetime('now', '-5 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-55', 'user-seed-73', 'user-seed-40', 'What''s your DUPR?', datetime('now', '-6 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-56', 'user-seed-86', 'user-seed-57', 'Great game today!', datetime('now', '-7 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-57', 'user-seed-99', 'user-seed-74', 'Hey, still on for Saturday?', datetime('now', '-1 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-58', 'user-seed-112', 'user-seed-91', 'Yes! Court 2 at 10.', datetime('now', '-2 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-59', 'user-demo-5', 'user-seed-108', 'Perfect, see you then.', datetime('now', '-3 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-60', 'user-seed-13', 'user-demo-5', 'Running 5 min late.', datetime('now', '-4 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-61', 'user-seed-26', 'user-seed-17', 'Need a fourth?', datetime('now', '-5 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-62', 'user-seed-39', 'user-seed-34', 'I''m in for tomorrow.', datetime('now', '-6 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-63', 'user-seed-52', 'user-seed-51', 'What''s your DUPR?', datetime('now', '-7 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-64', 'user-seed-65', 'user-seed-68', 'Great game today!', datetime('now', '-1 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-65', 'user-seed-78', 'user-seed-85', 'Hey, still on for Saturday?', datetime('now', '-2 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-66', 'user-seed-91', 'user-seed-102', 'Yes! Court 2 at 10.', datetime('now', '-3 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-67', 'user-seed-104', 'user-seed-119', 'Perfect, see you then.', datetime('now', '-4 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-68', 'user-seed-117', 'user-seed-11', 'Running 5 min late.', datetime('now', '-5 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-69', 'user-seed-5', 'user-seed-28', 'Need a fourth?', datetime('now', '-6 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-70', 'user-seed-18', 'user-seed-45', 'I''m in for tomorrow.', datetime('now', '-7 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-71', 'user-seed-31', 'user-seed-62', 'What''s your DUPR?', datetime('now', '-1 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-72', 'user-seed-44', 'user-seed-79', 'Great game today!', datetime('now', '-2 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-73', 'user-seed-57', 'user-seed-96', 'Hey, still on for Saturday?', datetime('now', '-3 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-74', 'user-seed-70', 'user-seed-113', 'Yes! Court 2 at 10.', datetime('now', '-4 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-75', 'user-seed-83', 'user-seed-5', 'Perfect, see you then.', datetime('now', '-5 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-76', 'user-seed-96', 'user-seed-22', 'Running 5 min late.', datetime('now', '-6 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-77', 'user-seed-109', 'user-seed-39', 'Need a fourth?', datetime('now', '-7 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-78', 'user-demo-2', 'user-seed-56', 'I''m in for tomorrow.', datetime('now', '-1 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-79', 'user-seed-10', 'user-seed-73', 'What''s your DUPR?', datetime('now', '-2 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-80', 'user-seed-23', 'user-seed-90', 'Great game today!', datetime('now', '-3 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-81', 'user-seed-36', 'user-seed-107', 'Hey, still on for Saturday?', datetime('now', '-4 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-82', 'user-seed-49', 'user-demo-4', 'Yes! Court 2 at 10.', datetime('now', '-5 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-83', 'user-seed-62', 'user-seed-16', 'Perfect, see you then.', datetime('now', '-6 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-84', 'user-seed-75', 'user-seed-33', 'Running 5 min late.', datetime('now', '-7 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-85', 'user-seed-88', 'user-seed-50', 'Need a fourth?', datetime('now', '-1 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-86', 'user-seed-101', 'user-seed-67', 'I''m in for tomorrow.', datetime('now', '-2 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-87', 'user-seed-114', 'user-seed-84', 'What''s your DUPR?', datetime('now', '-3 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-88', 'user-seed-2', 'user-seed-101', 'Great game today!', datetime('now', '-4 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-89', 'user-seed-15', 'user-seed-118', 'Hey, still on for Saturday?', datetime('now', '-5 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-90', 'user-seed-28', 'user-seed-10', 'Yes! Court 2 at 10.', datetime('now', '-6 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-91', 'user-seed-41', 'user-seed-27', 'Perfect, see you then.', datetime('now', '-7 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-92', 'user-seed-54', 'user-seed-44', 'Running 5 min late.', datetime('now', '-1 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-93', 'user-seed-67', 'user-seed-61', 'Need a fourth?', datetime('now', '-2 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-94', 'user-seed-80', 'user-seed-78', 'I''m in for tomorrow.', datetime('now', '-3 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-95', 'user-seed-93', 'user-seed-95', 'What''s your DUPR?', datetime('now', '-4 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-96', 'user-seed-106', 'user-seed-112', 'Great game today!', datetime('now', '-5 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-97', 'user-seed-119', 'user-seed-4', 'Hey, still on for Saturday?', datetime('now', '-6 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-98', 'user-seed-7', 'user-seed-21', 'Yes! Court 2 at 10.', datetime('now', '-7 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-99', 'user-seed-20', 'user-seed-38', 'Perfect, see you then.', datetime('now', '-1 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-100', 'user-seed-33', 'user-seed-55', 'Running 5 min late.', datetime('now', '-2 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-101', 'user-seed-46', 'user-seed-72', 'Need a fourth?', datetime('now', '-3 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-102', 'user-seed-59', 'user-seed-89', 'I''m in for tomorrow.', datetime('now', '-4 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-103', 'user-seed-72', 'user-seed-106', 'What''s your DUPR?', datetime('now', '-5 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-104', 'user-seed-85', 'user-demo-3', 'Great game today!', datetime('now', '-6 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-105', 'user-seed-98', 'user-seed-15', 'Hey, still on for Saturday?', datetime('now', '-7 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-106', 'user-seed-111', 'user-seed-32', 'Yes! Court 2 at 10.', datetime('now', '-1 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-107', 'user-demo-4', 'user-seed-49', 'Perfect, see you then.', datetime('now', '-2 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-108', 'user-seed-12', 'user-seed-66', 'Running 5 min late.', datetime('now', '-3 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-109', 'user-seed-25', 'user-seed-83', 'Need a fourth?', datetime('now', '-4 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-110', 'user-seed-38', 'user-seed-100', 'I''m in for tomorrow.', datetime('now', '-5 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-111', 'user-seed-51', 'user-seed-117', 'What''s your DUPR?', datetime('now', '-6 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-112', 'user-seed-64', 'user-seed-9', 'Great game today!', datetime('now', '-7 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-113', 'user-seed-77', 'user-seed-26', 'Hey, still on for Saturday?', datetime('now', '-1 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-114', 'user-seed-90', 'user-seed-43', 'Yes! Court 2 at 10.', datetime('now', '-2 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-115', 'user-seed-103', 'user-seed-60', 'Perfect, see you then.', datetime('now', '-3 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-116', 'user-seed-116', 'user-seed-77', 'Running 5 min late.', datetime('now', '-4 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-117', 'user-seed-4', 'user-seed-94', 'Need a fourth?', datetime('now', '-5 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-118', 'user-seed-17', 'user-seed-111', 'I''m in for tomorrow.', datetime('now', '-6 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-119', 'user-seed-30', 'user-seed-3', 'What''s your DUPR?', datetime('now', '-7 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-120', 'user-seed-43', 'user-seed-20', 'Great game today!', datetime('now', '-1 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-121', 'user-seed-56', 'user-seed-37', 'Hey, still on for Saturday?', datetime('now', '-2 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-122', 'user-seed-69', 'user-seed-54', 'Yes! Court 2 at 10.', datetime('now', '-3 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-123', 'user-seed-82', 'user-seed-71', 'Perfect, see you then.', datetime('now', '-4 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-124', 'user-seed-95', 'user-seed-88', 'Running 5 min late.', datetime('now', '-5 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-125', 'user-seed-108', 'user-seed-105', 'Need a fourth?', datetime('now', '-6 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-126', 'user-demo-1', 'user-demo-2', 'I''m in for tomorrow.', datetime('now', '-7 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-127', 'user-seed-9', 'user-seed-14', 'What''s your DUPR?', datetime('now', '-1 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-128', 'user-seed-22', 'user-seed-31', 'Great game today!', datetime('now', '-2 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-129', 'user-seed-35', 'user-seed-48', 'Hey, still on for Saturday?', datetime('now', '-3 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-130', 'user-seed-48', 'user-seed-65', 'Yes! Court 2 at 10.', datetime('now', '-4 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-131', 'user-seed-61', 'user-seed-82', 'Perfect, see you then.', datetime('now', '-5 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-132', 'user-seed-74', 'user-seed-99', 'Running 5 min late.', datetime('now', '-6 days'), datetime('now', '-1 days'));
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-133', 'user-seed-87', 'user-seed-116', 'Need a fourth?', datetime('now', '-7 days'), NULL);
INSERT OR IGNORE INTO messages (id, sender_id, receiver_id, content, created_at, read_at) VALUES ('msg-seed-134', 'user-seed-100', 'user-seed-8', 'I''m in for tomorrow.', datetime('now', '-1 days'), datetime('now', '-1 days'));
