INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-4', 'user-seed-7', 4, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-4', 'user-seed-8', 5, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-4', 'user-seed-9', 6, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-4', 'user-seed-10', 7, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-4', 'user-seed-11', 8, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-4', 'user-seed-12', 9, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-4', 'user-seed-13', 10, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-4', 'user-seed-14', 11, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-4', 'user-seed-15', 12, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-4', 'user-seed-16', 13, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-4', 'user-seed-17', 14, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-4', 'user-seed-18', 15, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-4', 'user-seed-19', 16, datetime('now'));
INSERT OR IGNORE INTO tournaments (id, name, admin_id, status, created_at) VALUES ('tournament-seed-5', 'Seed Tournament 5', 'user-demo-5', 'completed', datetime('now', '-10 days'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-5', 'user-seed-6', 1, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-5', 'user-seed-7', 2, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-5', 'user-seed-8', 3, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-5', 'user-seed-9', 4, datetime('now'));
INSERT OR IGNORE INTO tournaments (id, name, admin_id, status, created_at) VALUES ('tournament-seed-6', 'Seed Tournament 6', 'user-seed-1', 'draft', datetime('now', '-11 days'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-6', 'user-seed-8', 1, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-6', 'user-seed-9', 2, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-6', 'user-seed-10', 3, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-6', 'user-seed-11', 4, datetime('now'));
INSERT OR IGNORE INTO tournaments (id, name, admin_id, status, created_at) VALUES ('tournament-seed-7', 'Seed Tournament 7', 'user-seed-2', 'in_progress', datetime('now', '-12 days'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-7', 'user-seed-10', 1, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-7', 'user-seed-11', 2, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-7', 'user-seed-12', 3, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-7', 'user-seed-13', 4, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-7', 'user-seed-14', 5, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-7', 'user-seed-15', 6, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-7', 'user-seed-16', 7, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-7', 'user-seed-17', 8, datetime('now'));
INSERT OR IGNORE INTO tournaments (id, name, admin_id, status, created_at) VALUES ('tournament-seed-8', 'Seed Tournament 8', 'user-seed-3', 'completed', datetime('now', '-13 days'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-8', 'user-seed-12', 1, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-8', 'user-seed-13', 2, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-8', 'user-seed-14', 3, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-8', 'user-seed-15', 4, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-8', 'user-seed-16', 5, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-8', 'user-seed-17', 6, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-8', 'user-seed-18', 7, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-8', 'user-seed-19', 8, datetime('now'));
INSERT OR IGNORE INTO tournaments (id, name, admin_id, status, created_at) VALUES ('tournament-seed-9', 'Seed Tournament 9', 'user-seed-4', 'draft', datetime('now', '-14 days'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-9', 'user-seed-14', 1, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-9', 'user-seed-15', 2, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-9', 'user-seed-16', 3, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-9', 'user-seed-17', 4, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-9', 'user-seed-18', 5, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-9', 'user-seed-19', 6, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-9', 'user-seed-20', 7, datetime('now'));
INSERT OR IGNORE INTO tournament_participants (tournament_id, user_id, seed, created_at) VALUES ('tournament-seed-9', 'user-seed-21', 8, datetime('now'));
