import { index, type RouteConfig, route } from "@react-router/dev/routes";

export default [
	index("routes/landing.tsx"),
	route("demo", "routes/demo.tsx"),
	route("home", "routes/home.tsx"),
	route("courts", "routes/courts.tsx"),
	route("courts/new", "routes/courts.new.tsx"),
	route("courts/:courtId", "routes/courts.$courtId.tsx"),
	route("sessions", "routes/sessions.tsx"),
	route("tournaments", "routes/tournaments.tsx"),
	route("guides", "routes/guides.tsx"),
	route("paddles", "routes/paddles.tsx"),
	route("paddles/:paddleId", "routes/paddles.$paddleId.tsx"),
	route("tournaments/:tournamentId", "routes/tournaments.$tournamentId.tsx"),
	route("join/:code", "routes/join.$code.tsx"),
	route("profile/:userId", "routes/profile.$userId.tsx"),
	route("api/avatar/:userId", "routes/api.avatar.$userId.tsx"),
	route("friends", "routes/friends.tsx"),
	route("messages", "routes/messages.tsx"),
	route("messages/:otherId", "routes/messages.$otherId.tsx"),
	route("auth/oauth/google", "routes/auth.oauth.google.tsx"),
	route("auth/oauth/google/callback", "routes/auth.oauth.google.callback.tsx"),
	route("auth/oauth/github", "routes/auth.oauth.github.tsx"),
	route("auth/oauth/github/callback", "routes/auth.oauth.github.callback.tsx"),
	route("auth/logout", "routes/auth.logout.tsx"),
] satisfies RouteConfig;
